In [1]:
import pandas as pd 
import numpy as np

## Parte 1: NUMPY:

#### 1) ¿Cuàl es el tamaño en bytes de un array de 1000 elementos de tipo de booleno?

In [3]:
array_1 = np.reshape(np.arange(1000),(10,100))
print(array_1)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
   54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
   72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
   90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
  136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
  154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
  172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
  190 191 192 193 194 195 196 197 198 199]
 [200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
  218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
  236 237 238 239 240 241 

#### 2) Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [15]:
dos = np.arange(0,1002,2)
dos[::-1].sort()
dos[-10:]


array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

#### 3) Dado el array, seleccione con una instrucción el subarray de elementos 0374


In [23]:
array3 = np.array([[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]])
print(array3)
array3[1]

[[2 4 5 6]
 [0 3 7 4]
 [8 8 5 2]
 [1 5 6 1]]


array([0, 3, 7, 4])

#### Después, seleccione el subarray de elementos

In [58]:
arr1 = array3[0,0]
arr2 = array3[0,2]
arr3 = array3[2,0]
arr4 = array3[2,2]
arr = np.array([[arr1,arr2],[arr3,arr4]])
print(f"{arr1},{arr2},{arr3},{arr4}, conviertiendolo a un arreglo{arr}")

2,5,8,5, conviertiendolo a un arreglo[[2 5]
 [8 5]]


#### 4) Dados los arrays a = [1,4,2,7] y b = [1,3,2,9], obtenga la media artiméticade la diferencia de (a-b)

In [66]:
a = np.array([1,4,2,7])
b = np.array([1,3,2,9])
c = np.average(a - b)
print(f"la media aritmética es : {c}")


la media aritmética es : -0.25


#### 5) Tengo valores de cordenadas (x,y) en las columnas del array 1.33 4.5 30.0 10.7 70.2 0.5

#### Agregue a este array las coordenadas (37.1, -3.6)

In [68]:
cinco = np.array([[1.33,4.5],[30.0,10.7],[70.2,0.5]])
cinco

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ]])

In [76]:
respuesta5 = np.append(cinco,np.array([[37.1,-3.5]]),axis=0)
respuesta5

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.5 ]])

#### 6) Copie el array del ejercicio anterior. Traspóngalo, agregue ahora dos nuevos pares de coordenadas: (10.8,3.0) y (35.8,12.0)

In [101]:
respuesta_5 = respuesta5.transpose()
respuesta_5
respuesta_6 = np.append(respuesta_5, np.array([[10.8,3.0],[35.8,12.0]]),axis = 1)
respuesta_6

array([[ 1.33, 30.  , 70.2 , 37.1 , 10.8 ,  3.  ],
       [ 4.5 , 10.7 ,  0.5 , -3.5 , 35.8 , 12.  ]])

## Parte 2: EXPLORACION Y MINERIA DE DATOS

In [144]:
nucleos = np.loadtxt('NucleosPoblacion.csv',delimiter=",",dtype=str)
nucleos

array([['FID', 'OBJECTID', 'Texto', ..., 'Provincia', 'X', 'Y'],
       ['0', '1', 'Agüimes', ..., 'Las Palmas', '-15.446012264',
        '27.9005418852'],
       ['1', '2', 'Antigua', ..., 'Las Palmas', '-14.01330083',
        '28.4189662242'],
       ...,
       ['849', '850', 'Vista Alegre', ..., 'Murcia', '-1.130563853',
        '37.9957145751'],
       ['850', '851', 'Poligono Sta M de Benquerencia', ..., 'Toledo',
        '-3.948363664', '39.8666989761'],
       ['851', '852', 'Grao', ..., 'Castelló/Castellón', '0.012911354',
        '39.9735678251']], dtype='<U47')

In [145]:
nucleos_poblacion = pd.DataFrame(nucleos)


In [146]:
nucleos_poblacion.columns = nucleos_poblacion.iloc[0]


In [147]:
nucleos_poblacion.drop(0,axis = 0, inplace = True)




In [148]:
nucleos_poblacion

0    FID OBJECTID                           Texto Poblacion CodMun  \
1      0        1                         Agüimes   29431.0  35002   
2      1        2                         Antigua   10458.0  35003   
3      2        3                        Arrecife   58156.0  35004   
4      3        4                          Arucas   36745.0  35006   
5      4        5                          Gáldar   24473.0  35009   
..   ...      ...                             ...       ...    ...   
848  847      848             Infante Juan Manuel   14192.0  30030   
849  848      849           Santa Maria de Gracia   13349.0  30030   
850  849      850                    Vista Alegre   15208.0  30030   
851  850      851  Poligono Sta M de Benquerencia   19177.0  45168   
852  851      852                            Grao   16367.0  12040   

0                                     Municipio CodProvin           Provincia  \
1                                       Agüimes        35          Las Palmas   
2                                       Antigua        35          Las Palmas   
3                                      Arrecife        35          Las Palmas   
4                                        Arucas        35          Las Palmas   
5                                        Gáldar        35          Las Palmas   
..                                          ...       ...                 ...   
848                                      Murcia        30              Murcia   
849                                      Murcia        30              Murcia   
850                                      Murcia        30              Murcia   
851                                      Toledo        45              Toledo   
852  Castellón de la Plana/Castelló de la Plana        12  Castelló/Castellón   

0                X              Y  
1    -15.446012264  27.9005418852  
2     -14.01330083  28.4189662242  
3    -13.551451235  28.9606494152  
4    -15.521511534  28.1174962002  
5    -15.654110983  28.1438727542  
..             ...            ...  
848   -1.124304406  37.9790332151  
849   -1.202068979  37.9840238301  
850   -1.130563853  37.9957145751  
851   -3.948363664  39.8666989761  
852    0.012911354  39.9735678251  

[852 rows x 10 columns]

## 1.

In [153]:
nucleos_poblacion.loc[(nucleos_poblacion['Poblacion']>=1000)]

TypeError: '>=' not supported between instances of 'str' and 'int'